config/routes.rb
Rails.application.routes.draw do
  resources :pieces
  resources :covers
  resources :rules
  resources :games
  root to: "games#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cover.rb
class Cover < ApplicationRecord
  belongs_to :game

  # el cover tiene una imagen
  has_one_attached :cover_photo

  validates :cover_photo, presence: true, blob: {content_type: ['image/png', 'image/jpg', 'image/jpeg']}
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :rule
  has_one :cover, dependent: :destroy
  has_many :pieces, dependent: :destroy
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :game

  has_many_attached :pieces_photos

  validates :pieces_photos, presence: true, blob: {content_type: ['image/png', 'image/jpg', 'image/jpeg']}
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :game

  has_one_attached :doc_rule

  validates :doc_rule, presence: true, blob: {content_type: :pdf}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/covers_controller.rb
class CoversController < ApplicationController
  before_action :set_cover, only: %i[ show edit update destroy ]

  # GET /covers or /covers.json
  def index
    @covers = Cover.all
  end

  # GET /covers/1 or /covers/1.json
  def show
  end

  # GET /covers/new
  def new
    @cover = Cover.new
  end

  # GET /covers/1/edit
  def edit
  end

  # POST /covers or /covers.json
  def create
    @cover = Cover.new(cover_params)

    respond_to do |format|
      if @cover.save
        format.html { redirect_to cover_url(@cover), notice: "Cover was successfully created." }
        format.json { render :show, status: :created, location: @cover }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /covers/1 or /covers/1.json
  def update
    respond_to do |format|
      if @cover.update(cover_params)
        format.html { redirect_to cover_url(@cover), notice: "Cover was successfully updated." }
        format.json { render :show, status: :ok, location: @cover }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covers/1 or /covers/1.json
  def destroy
    @cover.destroy

    respond_to do |format|
      format.html { redirect_to covers_url, notice: "Cover was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cover
      @cover = Cover.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cover_params
      params.require(:cover).permit(:game_id, :cover_photo)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all.includes(:pieces)
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :set_piece, only: %i[ show edit update destroy ]

  # GET /pieces or /pieces.json
  def index
    @pieces = Piece.all
  end

  # GET /pieces/1 or /pieces/1.json
  def show
  end

  # GET /pieces/new
  def new
    @piece = Piece.new
  end

  # GET /pieces/1/edit
  def edit
  end

  # POST /pieces or /pieces.json
  def create
    @piece = Piece.new(piece_params)

    respond_to do |format|
      if @piece.save
        format.html { redirect_to piece_url(@piece), notice: "Piece was successfully created." }
        format.json { render :show, status: :created, location: @piece }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pieces/1 or /pieces/1.json
  def update
    respond_to do |format|
      if @piece.update(piece_params)
        format.html { redirect_to piece_url(@piece), notice: "Piece was successfully updated." }
        format.json { render :show, status: :ok, location: @piece }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1 or /pieces/1.json
  def destroy
    @piece.destroy

    respond_to do |format|
      format.html { redirect_to pieces_url, notice: "Piece was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece
      @piece = Piece.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def piece_params
      params.require(:piece).permit(:game_id, pieces_photos: [])
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: %i[ show edit update destroy ]

  # GET /rules or /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1 or /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules or /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to rule_url(@rule), notice: "Rule was successfully created." }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1 or /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to rule_url(@rule), notice: "Rule was successfully updated." }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1 or /rules/1.json
  def destroy
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url, notice: "Rule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rule_params
      params.require(:rule).permit(:game_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/covers/_form.html.erb
<%= form_with(model: cover, local: true) do |form| %>
  <% if cover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cover.errors.count, "error") %> prohibited this cover from being saved:</h2>

      <ul>
      <% cover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id, "Game_id" %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :cover_photo %>
    <%= form.file_field :cover_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/covers/edit.html.erb
<h1>Editing Cover</h1>

<%= render 'form', cover: @cover %>

<%= link_to 'Show', @cover %> |
<%= link_to 'Back', covers_path %>

app/views/covers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Covers</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @covers.each do |cover| %>
      <tr>
        <td><%= cover.game %></td>
        <td><%= link_to 'Show', cover %></td>
        <td><%= link_to 'Edit', edit_cover_path(cover) %></td>
        <td><%= link_to 'Destroy', cover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cover', new_cover_path %>

app/views/covers/new.html.erb
<h1>New Cover</h1>

<%= render 'form', cover: @cover %>

<%= link_to 'Back', covers_path %>

app/views/covers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @cover.game %>
</p>

<%= link_to 'Edit', edit_cover_path(@cover) %> |
<%= link_to 'Back', covers_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rules</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= link_to "Ver", game.rule %></td>
        <td><%= image_tag game.cover.cover_photo.variant(resize: "100x100", colorspace: "gray").processed %></td>
        <td><%= link_to "Download", rails_blob_path(game.cover.cover_photo), disposition: "attachment" %></td>
        <td>
          <ul>
            <% game.pieces.each do |piece| %>
              <% piece.pieces_photos.each do |p| %>
                <li><%= image_tag p.variant(resize: "100x100", colorspace: "gray").processed %> </li>
              <% end %>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistroDeJuegos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pieces/_form.html.erb
<%= form_with(model: piece, local: true) do |form| %>
  <% if piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% piece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id, "Game_id" %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :pieces_photos %>
    <%= form.file_field :pieces_photos, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<h1>Editing Piece</h1>

<%= render 'form', piece: @piece %>

<%= link_to 'Show', @piece %> |
<%= link_to 'Back', pieces_path %>

app/views/pieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pieces</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pieces.each do |piece| %>
      <tr>
        <td><%= piece.game %></td>
        <td><%= link_to 'Show', piece %></td>
        <td><%= link_to 'Edit', edit_piece_path(piece) %></td>
        <td><%= link_to 'Destroy', piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Piece', new_piece_path %>

app/views/pieces/new.html.erb
<h1>New Piece</h1>

<%= render 'form', piece: @piece %>

<%= link_to 'Back', pieces_path %>

app/views/pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @piece.game %>
</p>

<%= link_to 'Edit', edit_piece_path(@piece) %> |
<%= link_to 'Back', pieces_path %>

app/views/rules/_form.html.erb
<%= form_with(model: rule, local: true) do |form| %>
  <% if rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id, "Game_id" %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :doc_rule %>
    <%= form.file_field :doc_rule %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing Rule</h1>

<%= render 'form', rule: @rule %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rules</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.game %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New Rule</h1>

<%= render 'form', rule: @rule %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @rule.game %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>